<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\TestAnimalsHandler::class => App\Handler\TestAnimalsHandlerFactory::class,
            App\Handler\TestIncludeHandler::class => App\Handler\TestIncludeHandlerFactory::class,
            App\Handler\TestPageHandler::class => App\Handler\TestPageHandlerFactory::class,
        ],
    ],
];
